### PR TITLE
Use ethash_blockhash_t in the codebase

### PR DESCRIPTION
**Pull request by LefterisJP**
Depends on #11.

- Using a typedef struct instead of passing an array of hard coded
  length of 32 bytes everywhere. It's much better C practise and also
  gives us typechecking.

- Also corrected style in places I touched. I think a style PR should
  follow after that.

### CODE REVIEW

**Comment by xcthulhu** [comment]
A lot of these refactorings break ethash.go

You might consider getting `go test ./...` to pass before you continue down this path.

**Comment by LefterisJP** [comment]
yes, there is a reason this is not merged yet. Lack of proper continuous integration testing for this repo does not help either :(

**Comment by LefterisJP** [comment]
Rebased on top of master.

**Comment by xcthulhu** [comment]
It looks like you need to refactor pyethash.

Incidentally, the javascript implementation is broken.  I started working on fixing it but my progress got reverted.  It's probably a good idea to make an npm module that wraps the C code to enable mining on the testnet with node-ethereum.

**Comment by LefterisJP** [comment]
yeah just noticed that the python stuff fails now. One fix per commit :)

We will see what to do about the JS implementation. The suggestion sounds nice but I am no javascript expert so I would have to investigate further.

**Comment by xcthulhu** [comment]
In that case you might consider deleting `io.c` and migrating it over to cpp-ethereum.

(1) On non-SDD drives it takes longer to load the DAG from disk than it does to build it in memory from scratch
(2) `ethash.go` uses a different mechanism anyway
(3) It's not necessary, just "good to have"

Better to have javascript support.

**Comment by LefterisJP** [comment]
The plan is for DAG IO writting to move to the C library. This is the whole reason this thing started.

**Comment by xcthulhu** [comment]
Incidentally, you are going to have to update pypi with the new module information for pyethash after this refactoring.

**Comment by LefterisJP** [comment]
yes I did not make any API changes here, just made it compile for the changes this PR is introducing.

**Comment by xcthulhu** [comment]
The Python 3 stuff requires a push to pypi, so I'll raise an issue.

**Comment by LefterisJP** [comment]
Note: Please do not merge until go tests also pass.

**Comment by LefterisJP** [comment]
gotests now pass with the latest commit. Have to manually run them since they are not integrated into travis yet due to a recent change.

**Comment by obscuren** [comment]
Go changes are fine

**Pull request merged**
