### PR TITLE
Integrating ethash-cl changes from cppethereum

### PR DESCRIPTION
**Pull request by LefterisJP**

### CODE REVIEW

**Comment by gavofyork** [comment]
looks about right; except that cl.hpp is missing...

**Comment by LefterisJP** [comment]
Hmmm you are right, in cpp-ethereum we have it. But why? I would expect us to use the system's OpenCL cpp wrapper header.

In my system they are quite similar apart from a const return.

```
diff --git a/usr/include/CL/cl.hpp b/home/lefteris/ew/cpp-ethereum/libethash-cl/cl.hpp
index 99b86a6..a384987 100644
--- a/usr/include/CL/cl.hpp
+++ b/home/lefteris/ew/cpp-ethereum/libethash-cl/cl.hpp
@@ -21,6 +21,8 @@
  * MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.
  ******************************************************************************/
 
+#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
+
 /*! \file
  *
  *   \brief C++ bindings for OpenCL 1.0 (rev 48) and OpenCL 1.1 (rev 33)    
@@ -239,7 +241,7 @@ public:
      *
      *  \return The error code.
      */
-    const cl_int err(void) const { return err_; }
+       cl_int err(void) const { return err_; }
 };
 
 #define __ERR_STR(x) #x
@@ -941,9 +943,9 @@ struct param_traits<detail:: token,param_name>       \
     typedef T param_type;                            \
 };
 
-__PARAM_NAME_INFO_1_0(__DECLARE_PARAM_TRAITS);
+__PARAM_NAME_INFO_1_0(__DECLARE_PARAM_TRAITS)
 #if defined(CL_VERSION_1_1)
-__PARAM_NAME_INFO_1_1(__DECLARE_PARAM_TRAITS);
+__PARAM_NAME_INFO_1_1(__DECLARE_PARAM_TRAITS)
 #endif // CL_VERSION_1_1
 
 #if defined(USE_CL_DEVICE_FISSION)
@@ -3395,6 +3397,7 @@ inline KernelFunctor::KernelFunctor(const KernelFunctor& rhs) :
 
 Event KernelFunctor::operator()(const VECTOR_CLASS<Event>* events)
 {
+       (void)events;
     Event event;
 
     err_ = queue_.enqueueNDRangeKernel(

```

**Comment by gavofyork** [comment]
mainly because the system one is flawed (on my system).

**Comment by LefterisJP** [comment]
Tested with @yann300 on an Ubunty 14.04 and the system OpenCL header was sufficient.

**Pull request merged**
