### PR TITLE
printf logging for ethash_full_new() errors

### PR DESCRIPTION
**Pull request by LefterisJP**

### CODE REVIEW

**Comment by fjl** [comment]
A dream: Would be nice if `ethash_full_new_internal` would set `errno` instead  the message were from `ethash_full_new`. This way, we could print the error in Go using the logging infrastructure and abort properly instead of crashing the whole thing like we do now.

**Comment by fjl** [comment]
Setting `errno` wouldn't be an API change.

**Comment by fjl** [comment]
Maybe consider using the POSIX constants (`EIO`, `EFBIG`, `EOVERFLOW`, etc.)

**Comment by LefterisJP** [comment]
Yeah keep forgetting you can access all C variables from GO. Setting errno would be a nice idea.

**Comment by fjl** [comment]
Btw, relevant snippet from the cgo docs:  You don't need to implement this in ethash.go because
we need to make other changes in go-ethereum first in order to handle errors during mining.

>  Any C function (even void functions) may be called in a multiple assignment context to retrieve both the return value (if any) and the C errno variable as an error (use _ to skip the result value if the function returns void). For example:

    n, err := C.sqrt(-1)
    _, err := C.voidFunc()

**Comment by LefterisJP** [comment]
Awesome. And I assume you can just call the Go equivalent of `strerror()` to get a user readable string. Will add it soon.

**Comment by LefterisJP** [comment]
@fjl done. I will leave it to you to implement it in Go ethereum whenever you want since you asked.

I checked all Windows system calls we make and they should all be setting `errno` just like their Posix equivalents albeit with a little bit less variety.

I also disabled the printf printing for GO.

**Comment by subtly** [comment]
Calling printf isn't the right way to do this. There are other issues such as -- where was the file created, what was it's size, and what was the error?  This information should make it's way up to the originating caller and not a log. Then the caller can determine what to do -- inform the user, log a message, exit, etc. The log message is a nicety (for us) however the clients need to handle the errors.

A request: Please wait to merge until today's fixes are in.

**Comment by LefterisJP** [comment]
We have already discussed this with @gavofyork. He has requested a minimal API where a failure is just that, a failure. This PR adds some extra info and makes sure `errno` is useful. 

For all those cases you mentioned there is only one answer which can be looked up in the [spec](https://github.com/ethereum/wiki/wiki/Ethash-DAG).

* Where was the file created?
    - Mac/Linux: $(HOME)/.ethash/full-R[REVISION]-[SEEDHASH]
    - Windows: $(HOME)/Appdata/Ethash/full-R[REVISION]-[SEEDHASH]

* what was it's size?
    - `ethash_get_datasize(seedhash)`

If any of these do not happen `errno` is set. The printf is temporary and can be disabled by `-DETHASH_NO_CRITICAL_OUTPUT`. The clients will then check `errno` in case of error and provide a reason as to why `ethash_full_new()` failed in whatever way they see fit.

What fixes are you referring to?

**Pull request merged**
