### PR TITLE
Fix endian swapping code

### PR DESCRIPTION
**Pull request by LefterisJP**
- The endian swapping code was actually doing bit-level swapping. Fixed
  that now and added some tests.

- Also removed ugly #ifdefs from the code and abstracted it all into
  macros which take care of the #ifdef logic

### CODE REVIEW

**Comment by LefterisJP** [comment]
Note: Please don't merge yet, I will have to test with the windows machine manually that it compiles there.

**Comment by chfast** [comment]
You can remove SSE code too, if still there. Compiler with -march=native will do it for you (verified).

**Comment by LefterisJP** [comment]
yeah was discussing that with Heiko just now. Will test it but probably you are right. Thanks man.

**Comment by LefterisJP** [comment]
windows tests confirmed passing

**Comment by programmerTim** [comment]
Not on MSVC it won't.

**Comment by programmerTim** [comment]
It was endian swapping bits? Daft!

**Comment by programmerTim** [comment]
Also, the SSE code has never been enabled on GCC yet and it is currently
disabled since it needs a runtime check to be safe to use; not all x64 CPUs
support the required instructions.

**Comment by LefterisJP** [comment]
I will check about SSE later. I did see that it's always #defined to 0 at the moment. So I am making a mental note to play with it later. 

Probably there can be a clean nice way to abstract it in a completely cross-platform way and enable it with cmake. Will need to investigate.

**Comment by programmerTim** [comment]
You want to pull the runtime switch out of the loop rather than hiding the
missing functionality in a function call. This wants C++ templates to do
nicely but you can also use the poor man's C approach of multiple inclusion
and macros.

**Pull request merged**
