### PR TITLE
multiconfiguration appveyor build

### PR DESCRIPTION
**Pull request by debris**
We now have multiple appveyors builds.

- Win32 Release
- Win32 Debug
- Winx64 Release
- Winx64 Debug

### CODE REVIEW

**Comment by LefterisJP** [comment]
What exactly will this do? Can you please provide a description along with the PR?

Just define what multiconfiguration means. Debug and Release. Win32 and Win64?

**Comment by debris** [comment]
just look [here](https://ci.appveyor.com/project/LefterisJP/ethash/build/1.0.0.58)

**Comment by LefterisJP** [comment]
So just for the record I will edit your description.

**Comment by debris** [comment]
Looks like appveyor is tired... I've created an [issue](http://help.appveyor.com/discussions/questions/1222-appveyor-project-build-time) in their issue tracker. I've seen that they have quite good support, so hopefully they will resolve it soon :)

**Comment by LefterisJP** [comment]
So the problem here seems to be that build time exceeds the maximum amount of time alloted to the free plan.
https://ci.appveyor.com/project/LefterisJP/ethash/build/1.0.0.58/job/cw2dursxyd465gqn/messages

**Comment by gavofyork** [comment]
we can get a paid plan for the appveyor if it will help matters. @LefterisJP please arrange it with kelley.

**Pull request closed without merging**
